/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE identityBaseService PLEASE EDIT ../identity.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Identity } from '../../domain/factomskaffolder_db/identity';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Identity.service.ts
 */

/*
 * SCHEMA DB Identity
 *
	{
		chain_id: {
			type: 'String',
			required : true
		},
		entry_hash: {
			type: 'String',
			required : true
		},
		key_pairs: {
			type: 'Custom'
		},
		stage: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		identity: {
			type: Schema.ObjectId,
			ref : "Doctor"
		},
	}
 *
 */
@Injectable()
export class IdentityBaseService {

    contextUrl: string = environment.endpoint + '/identities';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * IdentityService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Identity): Observable<Identity> {
        return this.http
            .post<Identity>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * IdentityService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * IdentityService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): Observable<Identity> {
        return this.http
            .get<Identity>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * IdentityService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Identity[]> {
        return this.http
            .get<Identity[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * IdentityService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Identity): Observable<Identity> {
        return this.http
            .post<Identity>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
